name: Main

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Zip build files
        run: cp action.yml out/action.yml && zip -r out.zip out
      - uses: softprops/action-gh-release@v1
        name: Release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out.zip
